package, shtests: add csh workaround
The 1995 ksh93 distribution had a trick to allow invoking the build
script directly from csh without adding an unportable #! path. This
commit adds a tweaked version of that:

min_posix=/if/this/is/csh/ignore/the/error/message || exec sh $0:q $argv:q

This works because it can be parsed by both sh and csh. On (t)csh,
the sh assignment is interpreted as a command name, which of course
doesn't exist, so throws an error:

min_posix=/if/this/is/csh/ignore/the/error/message: Command not found.

The error cannot be suppressed, at least not in a way that will not
make the sh parser error out, so this is the best we can do. At
least (t)csh users can now build and test with the standard
commands without having to prefix 'sh'.

Also, in bin/shtests, the code to escape from an antique Bourne or
broken POSIX shell (see 20f8557c) is copied over from bin/package.

diff --git a/bin/shtests b/bin/shtests
--- a/bin/shtests
+++ b/bin/shtests
@@ -1,17 +1,35 @@
-# Wrapper script to run the ksh93 regression tests without requiring nmake.
-# By Martijn Dekker <martijn@inlv.org> 2020-05-14
+# Wrapper script to run the ksh93 regression tests directly.
+# By Martijn Dekker <martijn@inlv.org> 2020-05-14, 2023-03-17
 # Public domain. http://creativecommons.org/publicdomain/zero/1.0/
 #
 # The manual: bin/shtests --man
 # Brief help: bin/shtests --help
 #
 # By default, this runs your compiled arch/*/bin/ksh.
-#
-# Note: The test suite actually uses $SHELL to indicate the shell to test. But
-# we cannot use the $SHELL environment value on entry to this wrapper script,
-# as that is already used for the user's default login shell on most systems.
 
-# Process and remove any assignment-argument indicating the shell to test
+# Escape from a non-POSIX shell
+min_posix=/if/this/is/csh/ignore/the/error/message || exec sh $0:q $argv:q
+# ('test X -ef Y' is technically non-POSIX, but practically universal)
+min_posix='test / -ef / && path=Bad && case $PATH in (Bad) exit 1;; esac && '\
+'PWD=Bad && cd -P -- / && case $PWD in (/) ;; (*) exit 1;; esac && '\
+'! { ! case x in ( x ) : ${0##*/} || : $( : ) ;; esac; } && '\
+'trap "exit 0" 0 && exit 1'
+if	(eval "$min_posix") 2>/dev/null
+then	: good shell
+else	"$SHELL" -c "$min_posix" 2>/dev/null && exec "$SHELL" -- "$0" ${1+"$@"}
+	sh -c "$min_posix" 2>/dev/null && exec sh -- "$0" ${1+"$@"}
+	DEFPATH=`getconf PATH` 2>/dev/null || DEFPATH=/usr/xpg4/bin:/bin:/usr/bin:/sbin:/usr/sbin
+	PATH=$DEFPATH:$PATH
+	export PATH
+	sh -c "$min_posix" 2>/dev/null && exec sh -- "$0" ${1+"$@"}
+	echo "$0: Can't escape from obsolete or broken shell. Run me with a POSIX shell." >&2
+	exit 128
+fi
+
+# The test suite uses $SHELL to indicate the shell to test. But we cannot
+# use a $SHELL environment value inherited by this script, as that is
+# already used for the user's default login shell on most systems. So
+# allow inheriting $KSH instead, or passing SHELL= or KSH= as arguments.
 for arg do
 	case $arg in
 	( SHELL=* | KSH=* )
