ksh93: build system tweaks (re: abbd9ffa, a33a6ecc)
Not all the SHOPT_* symbols with values resulting from probes were
exposed by shopt.h yet; this commit fixes that for consistency and
to avoid future surprises. Some of them had their defaults probed
in the features/options iffe script instead.

src/cmd/ksh93/features/{externs,options},
src/cmd/ksh93/Mamfile:
- Move the probe code for SHOPT_{DEVFD,TEST_L,SYSRC} from
  features/options to Mamfile in 'make shopt.h', adding tweaks.
  It is nicer to have these in one place.
- The SHOPT_GLOBCASEDET probe needs to remain an iffe feature test
  as it would be too awkward to implement directly in the Mamefile.
  Make FEATURE/options (the header generated by features/options) a
  dependency of shopt.h and include it from shopt.h. This ensures
  the SHOPT_GLOBCASEDET symbol remains available to all files as
  everything now includes "shopt.h". So, other files now never need
  to #include "FEATURES/options" directly.
- Move the NV_PID (see a33a6ecc) and SHELLMAGIC tests from
  features/options to features/externs because these are not
  compile-time option tests. The data/variables.c file needs
  NV_PID, but it does not need to include FEATURE/externs directly
  since defs.h already includes it.
- In the SHELLMAGIC and _arg_extrabytes tests, search PATH for env
  instead of hardcoding /usr/bin/env. That path is practically
  standard now but not formally, so it's more correct this way.

diff --git a/src/cmd/ksh93/features/externs b/src/cmd/ksh93/features/externs
--- a/src/cmd/ksh93/features/externs
+++ b/src/cmd/ksh93/features/externs
@@ -11,6 +11,18 @@ extern	nice		int	(int)
 extern	setreuid	int	(uid_t,uid_t)
 extern	setregid	int	(gid_t,gid_t)
 
+tst	note{ does the system support #! interpreter paths }end cross{
+	cat > "$EXECROOT/file$$" <<!
+	#! $(command -v env) true
+	exit 1
+	!
+	chmod 755 "$EXECROOT/file$$"
+	if	"$EXECROOT/file$$" 2>/dev/null
+	then	echo "#define SHELLMAGIC	1"
+	fi
+	rm -f "$EXECROOT/file$$"
+}end
+
 tst	note{ determining default number of extra bytes per argument for arguments list }end output{
 	/*
 	 * Figure out if this OS requires extra bytes per argument
@@ -26,7 +38,7 @@ tst	note{ determining default number of extra bytes per argument for arguments l
 	 * So, operating systems are free to consume ARG_MAX space in whatever bizarre way they want, and
 	 * may even come up with more innovative ways to waste buffer space in future. This test assumes
 	 * that null terminators are included in the total, because why wouldn't they be? It builds a
-	 * dummy arguments list and tries fork(2)/execve(2) to figure how how many extra bytes to add to
+	 * dummy arguments list and tries fork(2)/execvp(2) to figure how how many extra bytes to add to
 	 * each argument to account for pointers and whatnot, and outputs that (_arg_extrabytes) as a
 	 * default value for command_xargs() in path.c. We still cannot entirely rely on this value on all
 	 * systems, so path_spawn() in path.c is able to increase it at runtime if E2BIG still occurs.
@@ -73,7 +85,7 @@ tst	note{ determining default number of extra bytes per argument for arguments l
 				while(bytec < argmax)
 				{
 					if(argc==0)
-						argv[argc] = "/usr/bin/env";
+						argv[argc] = "env";
 					else if(argc==1)
 						argv[argc] = "true";
 					else
@@ -83,13 +95,13 @@ tst	note{ determining default number of extra bytes per argument for arguments l
 					argc++;
 				}
 				argv[argc] = NULL;
-				if(execve(argv[0], argv, environ) < 0)
+				if(execvp(argv[0], argv) < 0)
 				{
 					if(errno == E2BIG)
 						return 1;
 					else
 					{
-						error(ERROR_SYSTEM|2, "execve failed");
+						error(ERROR_SYSTEM|2, "execvp failed");
 						return 2;
 					}
 				}
@@ -135,4 +147,40 @@ tst	note{ determining default number of extra bytes per argument for arguments l
 	}
 }end fail{
 	echo "#define _arg_extrabytes	sizeof(char*)	/* BUG: test failed; assuming pointer size */"
+}end
+
+tst	note{ determining size of PID variables }end output{
+	#include <ast.h>
+	#include <sfio.h>
+	int main(void)
+	{
+		const int s = sizeof(pid_t);
+		char *a;
+		Sfio_t *b;
+		/*
+		 * For $$, $PPID, ${.sh.pid} and ${.sh.ppid} to work correctly, the size
+		 * of pid_t must be one of the integer sizes supported by nv_getval().
+		 * If there is ever a system where this test returns 1, then both this
+		 * test and nv_getval() must learn a new integer size attribute.
+		 */
+		if(s==sizeof(int16_t))		/* union Value: sp */
+			a="NV_INTEGER|NV_SHORT";
+		else if(s==sizeof(int32_t))	/* union Value: lp */
+			a="NV_INTEGER";
+		else if(s==sizeof(Sflong_t))	/* union Value: llp */
+			a="NV_INTEGER|NV_LONG";
+		else
+			return 1;
+		/* write NV_PID attribute definition */
+		sfprintf(sfstdout,"#define NV_PID\t(%s)\t/* integer attribute(s) corresponding to sizeof(pid_t)==%d */\n",a,s);
+		/* show nice test result output on FD 9 */
+		b = sfstropen();
+		sfprintf(b," %s (%d bytes) ... ",a,s);
+		a = sfstruse(b);
+		write(9,a,strlen(a));
+		return 0;
+	}
+}end fail{
+	echo "$0: cannot determine size of PID variables" >&2
+	exit 1
 }end
