iffe: really abort on output{ fail (re: e20c0c6b, e72543a, b6bd981)
After further examining the iffe code I found that fail{ ... }end
as well as pass{ ... }end blocks are executed in iffe's current
environment, using a simple 'eval', with no safeguards whatsoever!

This does of course afford maximum flexibility... for example, a
block can 'exit 1' to abort the iffe run and the whole build with
it. We can use this to abort properly on fatal compilation errors.

src/cmd/INIT/iffe.sh:
- Complete the fail{ and pass{ documentation; it should really be
  known that they run in iffe's current environment.
- Make one change: for just the 'eval' command that runs these
  blocks, redirect standard error back to the saved $stderr file
  descriptor so these blocks can write error messages using the
  standard >&2 instead of the undocumented >&$stderr.

src/lib/**/features/*:
- Write error message to standard error and error out properly when
  an output{ ... }end block fails to compile, instead of writing an
  #error directive to error out later.

diff --git a/src/cmd/builtin/features/pty b/src/cmd/builtin/features/pty
--- a/src/cmd/builtin/features/pty
+++ b/src/cmd/builtin/features/pty
@@ -50,7 +50,8 @@ tst - -lm output{
 		return 0;
 	}
 }end fail{
-	echo '#error The output block in src/cmd/builtin/features/pty failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 extern	_getpty		char*		(int*, int, mode_t, int)
diff --git a/src/lib/libast/features/lib b/src/lib/libast/features/lib
--- a/src/lib/libast/features/lib
+++ b/src/lib/libast/features/lib
@@ -659,7 +659,8 @@ tst	- output{
 	}
 
 }end fail{
-	echo '#error The output block in src/lib/libast/features/lib failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	no64 note{ largefile 64 broken }end execute{
diff --git a/src/lib/libast/features/sizeof b/src/lib/libast/features/sizeof
--- a/src/lib/libast/features/sizeof
+++ b/src/lib/libast/features/sizeof
@@ -11,5 +11,6 @@ tst	- note{ sizeof(integral-type) }end output{
 		return 0;
 	}
 }end fail{
-	echo '#error The output block in src/lib/libast/features/sizeof failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
