iffe: really abort on output{ fail (re: e20c0c6b, e72543a, b6bd981)
After further examining the iffe code I found that fail{ ... }end
as well as pass{ ... }end blocks are executed in iffe's current
environment, using a simple 'eval', with no safeguards whatsoever!

This does of course afford maximum flexibility... for example, a
block can 'exit 1' to abort the iffe run and the whole build with
it. We can use this to abort properly on fatal compilation errors.

src/cmd/INIT/iffe.sh:
- Complete the fail{ and pass{ documentation; it should really be
  known that they run in iffe's current environment.
- Make one change: for just the 'eval' command that runs these
  blocks, redirect standard error back to the saved $stderr file
  descriptor so these blocks can write error messages using the
  standard >&2 instead of the undocumented >&$stderr.

src/lib/**/features/*:
- Write error message to standard error and error out properly when
  an output{ ... }end block fails to compile, instead of writing an
  #error directive to error out later.

diff --git a/src/lib/libast/features/common b/src/lib/libast/features/common
--- a/src/lib/libast/features/common
+++ b/src/lib/libast/features/common
@@ -319,7 +319,8 @@ tst	- output{
 		return 0;
 	}
 }end fail{
-	echo '#error Output block #2 in src/lib/libast/features/common failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	- -DN=1 - -DN=0 output{
diff --git a/src/lib/libast/features/float b/src/lib/libast/features/float
--- a/src/lib/libast/features/float
+++ b/src/lib/libast/features/float
@@ -890,7 +890,8 @@ tst	- note{ missing floating point limits }end output{
 		return 0;
 	}
 }end fail{
-	echo '#error Output block #1 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	- note{ double exponent bitfoolery }end output{
@@ -926,7 +927,8 @@ tst	- note{ double exponent bitfoolery }end output{
 		return 0;
 	}
 }end fail{
-	echo '#error Output block #2 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	- note{ long double exponent bitfoolery }end output{
@@ -962,7 +964,8 @@ tst	- note{ long double exponent bitfoolery }end output{
 		return 0;
 	}
 }end fail{
-	echo '#error Output block #3 in src/lib/libast/features/float failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	- -DN=1 - -DN=2 note{ _ast_fltmax_t maximum integral type }end output{
diff --git a/src/lib/libast/features/sfio b/src/lib/libast/features/sfio
--- a/src/lib/libast/features/sfio
+++ b/src/lib/libast/features/sfio
@@ -15,7 +15,8 @@ tst	- note{ number of bits in pointer }end output{
 		return 0;
 	}
 }end fail{
-	echo '#error The output block in src/lib/libast/features/sfio failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
 
 tst	tmp_rmfail note{ open files cannot be removed }end execute{
diff --git a/src/lib/libdll/features/dll b/src/lib/libdll/features/dll
--- a/src/lib/libdll/features/dll
+++ b/src/lib/libdll/features/dll
@@ -261,5 +261,6 @@ tst	- -lm output{
 		return 0;
 	}
 }end fail{
-	echo '#error The output block in src/lib/libdll/features/dll failed to compile. Rebuild with IFFEFLAGS=-d1 to debug.'
+	echo "$0: Output block failed to compile. Export IFFEFLAGS=-d1 to debug." >&2
+	exit 1
 }end
