Introduce usage of __builtin_unreachable() and noreturn (#248)
This commit adds an UNREACHABLE() macro that expands to either the
__builtin_unreachable() compiler builtin (for release builds) or
abort(3) (for development builds). This is used to mark code paths
that are never to be reached.

It also adds the 'noreturn' attribute to functions that never
return: path_exec(), sh_done() and sh_syntax(). The UNREACHABLE()
macro is not added after calling these.

The purpose of these is:
* to slightly improve GCC/Clang compiler optimizations;
* to fix a few compiler warnings;
* to add code clarity.

Changes of note:

src/cmd/ksh93/sh/io.c: outexcept():
- Avoid using __builtin_unreachable() here since errormsg can
  return despite using ERROR_system(1), as shp->jmplist->mode is
  temporarily set to 0. See: https://github.com/att/ast/issues/1336

src/cmd/ksh93/tests/io.sh:
- Add a regression test for the ksh2020 bug referenced above.

src/lib/libast/features/common:
- Detect the existence of either the C11 stdnoreturn.h header or
  the GCC noreturn attribute, preferring the former when available.
- Test for the existence of __builtin_unreachable(). Use it for
  release builds. On development builds, use abort() instead, which
  crahses reliably for debugging when unreachable code is reached.

Co-authored-by: Martijn Dekker <martijn@inlv.org>

diff --git a/src/lib/libast/features/common b/src/lib/libast/features/common
--- a/src/lib/libast/features/common
+++ b/src/lib/libast/features/common
@@ -1,5 +1,5 @@
 iff	AST_COMMON
-hdr	pthread,stdarg,stddef,stdint,inttypes,types,unistd
+hdr	pthread,stdarg,stddef,stdint,stdnoreturn,inttypes,types,unistd
 sys	types
 typ	long.double,size_t,ssize_t
 typ	__va_list stdio.h
@@ -145,6 +145,16 @@ cat{
 	#	define __EXTERN__(T,obj)	extern T obj
 	#	define __DEFINE__(T,obj,val)	T obj = val
 	#endif
+
+	#if !_hdr_stdnoreturn
+	#if defined(__GNUC__) && (__GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ > 4))
+	#define noreturn __attribute__((noreturn))
+	#else
+	#define noreturn
+	#endif /* __GNUC__ */
+	#else
+	#include <stdnoreturn.h>
+	#endif /* _hdr_stdnoreturn */
 }end
 
 if	tst - note{ <stdarg.h>+<wchar.h> works }end compile{
@@ -633,4 +643,38 @@ run{
 	#define __name_h		1
 	#endif
 	!
+}end
+
+tst - note{ does this compiler have __builtin_unreachable() }end output{
+	/*
+	 * To avoid optimizing out the __builtin_unreachable() test call while also avoiding
+	 * executing it, put it in a test function that is called with argc as the argument.
+	 * argc should never be zero on init, but hopefully optimizers aren't that smart.
+	 */
+	#include <stdio.h>
+	void testfn(int a)
+	{
+		switch(a)
+		{
+		case 0:
+			__builtin_unreachable();
+		default:
+			printf("#if _AST_ksh_release\n");
+			printf("#   define UNREACHABLE()\t__builtin_unreachable()\n");
+			printf("#else\n");
+			printf("#   define UNREACHABLE()\tabort()\n");
+			printf("#endif\n");
+		}
+	}
+	int main(int argc, char *argv[])
+	{
+		testfn(argc);
+		return 0;
+	}
+}end fail{
+	echo '#if _AST_ksh_release'
+	echo '#   define UNREACHABLE()	0'
+	echo '#else'
+	echo '#   define UNREACHABLE()	abort()'
+	echo '#endif'
 }end
