build: iffe tests: fix more direct-path invocations (re: b6b8b522)
src/lib/libast/features/lib,
src/lib/libast/features/siglist:
- Eliminate some overlooked direct-path invocations of external
  commands (/bin/cat, /bin/echo, /bin/kill). Invoke these via
  env(1) to ensure that they are found on $PATH as external
  commands. (re: b6b8b522)

src/lib/libast/features/libpath.sh,
src/lib/libdll/features/dll:
- Instead of obtaining the host type using a `package` invocation,
  just use $HOSTTYPE, which package(1) exports to the environment.
  This is more efficient.

diff --git a/src/lib/libast/features/siglist b/src/lib/libast/features/siglist
--- a/src/lib/libast/features/siglist
+++ b/src/lib/libast/features/siglist
@@ -1,7 +1,8 @@
 lib	strsignal string.h signal.h
 
 tst	- run{
-	for sig in `/bin/kill -l 2>/dev/null`
+	sig=$(env kill -l) || exit
+	for sig in $sig
 	do	case $sig in
 		*[!A-Za-z0-9_]*|*MIN|*MAX)
 			;;
@@ -11,4 +12,7 @@ tst	- run{
 			;;
 		esac
 	done
+}end fail{
+	echo "$0: failed to get list of signals from external 'kill -l'" >&2
+	exit 1
 }end
