Regression test suite: get rid of unportable 'mktemp -dt'
The regression test suite used 'mktemp -dt' to create temporary
directories, but that is not portable, e.g. it does not work on
macOS, FreebSD or NetBSD. Installing a compatible 'mktemp' in
another location in $PATH did not work either, as the regression
test suite resets $PATH.

src/cmd/ksh93/tests/*:
- Replace many uses of 'mktemp -dt' by a portable and reasonably
  safe way to create a temporary directory.

(cherry picked from commit 71f4c43703e3eff034009b4c8f4110bd32f4e209)

diff --git a/src/cmd/ksh93/tests/shtests b/src/cmd/ksh93/tests/shtests
--- a/src/cmd/ksh93/tests/shtests
+++ b/src/cmd/ksh93/tests/shtests
@@ -275,8 +275,14 @@ then	s=${SHELL:##*sh}
 fi
 if	(( compile ))
 then	if	whence $SHCOMP > /dev/null
-	then	tmp=$(mktemp -dt) || { echo mktemp -dt failed >&2; exit 1; }
-		trap "cd /; rm -rf $tmp" EXIT
+	then	tmp=$(
+			d=${TMPDIR:-/tmp}/ksh93.shtests.$$.${RANDOM:-0}
+			mkdir -m700 -- "$d" && CDPATH= cd -P -- "$d" && pwd
+		) || {
+			echo 'mkdir failed' >&2
+			exit 1
+		}
+		trap 'cd / && rm -rf "$tmp"' EXIT
 	elif	(( compile > 1 ))
 	then	echo $0: --compile: $SHCOMP not found >&2
 		exit 1
@@ -288,8 +294,14 @@ then	if	[[ -x $SHELL-g ]]
 	then	SHELL=$SHELL-g
 	fi
 	if	[[ ! $tmp ]]
-	then	tmp=$(mktemp -dt) || { echo mktemp -dt failed >&2; exit 1; }
-		trap "cd /; rm -rf $tmp" EXIT
+	then	tmp=$(
+			d=${TMPDIR:-/tmp}/ksh93.shtests.$$.${RANDOM:-0}
+			mkdir -m700 -- "$d" && CDPATH= cd -P -- "$d" && pwd
+		) || {
+			echo 'mkdir failed' >&2
+			exit 1
+		}
+		trap 'cd / && rm -rf "$tmp"' EXIT
 	fi
 	valxml=$tmp/valgrind.xml
 	valgrind+=" --xml-file=$valxml"
